
```{r setup, message=FALSE, warning=FALSE, echo=FALSE}
# Packages
library(tidync)
library(lubridate)
library(tidyverse)
library(knitr)
library(agroenv)

# options
opts_knit$set(root.dir = normalizePath('../'))
opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)

# extract climate data at given coordinates from hourly nc files
get_climate_nc <- function(file, grid_id) {
  
  value_origin <- ncmeta::nc_atts(file) %>%
    filter(name == "units", variable=="time") %>% 
    unnest(cols = c(value)) %>% 
    pull(value) %>% 
    substr(15, 33)
  
  # TODO tidync should be able to filter on non contiguous index  
  nc_subset <- tidync(file) %>%
    hyper_filter(Number_of_points = Number_of_points %in% grid_id)
  
  # get climate data from nc file
  data <- nc_subset %>% hyper_tibble()
  
  # add time variables and transform climate variables
  # hour correspond to the end of the time interval
  data_climate <- data %>% 
    mutate(
      grid_id = Number_of_points,
      rain = (Rainf + Snowf) * 3600,
      temperature = Tair - 273.15,
      date = seconds(time) %>% as_datetime(origin=value_origin),
      year = year(date),
      yday = yday(date),
      hour = hour(date)
    ) %>% 
    select(grid_id, date, year, yday, hour, rain, wind=Wind, temperature)
}

```


```{r metadata, eval=FALSE}
list_files <- list.files(path_climate, full.names = TRUE)

file <- list_files[1]

nc <- tidync(file)

data_grid <- nc %>% activate("D0") %>% hyper_tibble()

table_unit <- ncmeta::nc_atts(file) %>%
  filter(name == "units") %>% 
  unnest(cols = c(value)) 

```


```{r data_raw}
# path to hourly climate files
path_climate <- "~/Documents/INRA/Database/db_safran_hourly"

# list of locations to extract data
table_location <- tibble(
  id=c("Toulouse","Caen", "Montpellier", "Paris"),
  latitude = c(43.5279, 49.1305, 43.5555, 48.8042),
  longitude = c(1.5009, -0.3708, 3.8782, 2.3511)
  ) %>% 
  group_by(id) %>% 
  do(agroenv::get_station(.$latitude, .$longitude, network="safran")) %>% 
  rename(grid_id = station_id) %>% 
  ungroup()

list_grid <- table_location %>% slice(3)

# extract hourly climate data from a list of files
list_files <- list.files(path_climate, full.names = TRUE)

data_climate <- list_files[1:20] %>% map(get_climate_nc, grid_id=list_grid$grid_id)

# export
write_csv(table_location, "data/table_stations.csv")
write_rds(bind_rows(data_climate), paste0("data/priv/climate_",list_grid$grid_id,".rds"), compress="gz")
```

