```{r setup, message=FALSE, warning=FALSE, echo=FALSE}
# Packages
library(readr)
library(lubridate)
library(tidyverse)
library(broom)
library(modelr)
library(ggplot2)
library(gganimate)
library(knitr)

# options
opts_knit$set(root.dir = normalizePath('../'))
opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
options(knitr.kable.NA = '')
theme_set(theme_bw())

`%out%` <- function(a,b) ! a %in% b

value_dpi <- 200
```

```{r data_frequency, eval=FALSE}
# load table for available climate stations
table_stations <- read_csv("data/table_stations.csv")

# define range of year to study (full years only)
list_years <- 2000:2018

# threshold used to compute the frequency of moderate or strong rain events
threshold_rain <- 2

# define the range of hours to analyse
range_time <- data.frame(xmin=8, xmax=9, ymin=-Inf, ymax=Inf)

# load raw climate data
list_files <- list.files("data/priv", full.names = TRUE)

# add location id and order by rough geographical position
data_climate <- list_files %>% map_df(read_rds) %>% 
  left_join(table_stations) %>% 
  mutate(id = factor(id, levels = c("Caen", "Paris", "Toulouse", "Montpellier")))

# compute frequency of rain events during each daily commute
data_rain_year <- data_climate %>% 
  filter(year %in% list_years) %>% 
  group_by(id, grid_id, year, hour) %>% 
  summarise(
    n_total = n(),
    n_rain = length(rain[rain > 0]),
    n_rain_strong = length(rain[rain > threshold_rain]),
    n_rain_moderate = length(rain[rain <= threshold_rain & rain > 0])
  ) %>%
  group_by(id, grid_id, year) %>% 
  mutate(
    f_rain = n_rain / n_total,
    f_rain_strong =  n_rain_strong / n_total,
    f_rain_moderate =  n_rain_moderate / n_total,
    f_dry = 1 - f_rain,
    f_rain_delta = f_rain - lag(f_rain),
    ncm_dry = (f_dry * n_total) / 12,
    ncm_rain = (f_rain * n_total) / 12,
    ncm_rain_strong = (f_rain_strong * n_total) / 12,
    ncm_rain_delta = (f_rain_delta * n_total) / 12,
  ) %>% ungroup()

# compute frequency of rain events during each daily commute
data_rain_month <- data_climate %>% 
  filter(year %in% list_years) %>% 
  mutate(
    month = month(date),
    month_label = month(date, label = TRUE, locale = "C")
  ) %>% 
  group_by(id, grid_id, year, month, month_label, hour) %>% 
  summarise(
    n_total = n(),
    n_rain = length(rain[rain > 0]),
    n_rain_strong = length(rain[rain > threshold_rain]),
    n_rain_moderate = length(rain[rain <= threshold_rain & rain > 0])
  ) %>%
  group_by(id, grid_id, year, month) %>% 
  mutate(
    f_rain = n_rain / n_total,
    f_rain_strong =  n_rain_strong / n_total,
    f_rain_moderate =  n_rain_moderate / n_total,
    f_dry = 1 - f_rain,
    f_rain_delta = f_rain - lag(f_rain),
    n_rain_delta = (f_rain_delta * n_total),
  ) %>% ungroup()

# export processed data
write_rds(data_rain_year, "data/data_frequency_rain_year.rds", compress = "gz")
write_rds(data_rain_month, "data/data_frequency_rain_month.rds", compress = "gz")
```

```{r figures_static}

data_rain <- read_rds("data/data_frequency_rain_year.rds")

# plot frequency of a dry commute as a function of time   
plot_dry_model <- data_rain %>%
  ggplot(aes(x=hour, y=f_dry)) +
  geom_point(aes(color=year), alpha=0.5) + geom_smooth(se=FALSE) +
  geom_rect(
    data=range_time,
    aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax),
    inherit.aes = FALSE, alpha=0.5) +
  geom_hline(yintercept = 0.9, color="gray") +
  facet_wrap(facets = vars(id), ncol=2) +
  scale_color_viridis_c(name = "Year", end = 0.8, option = "plasma") +
  labs(
    x = "Time at arrival",
    y = "Frequency of a dry commute during a one hour interval"
  ) 

# plot number of rainy commutes per month as a function of time   
plot_rain_model <- data_rain %>%
  ggplot(aes(x=hour, y=ncm_rain)) +
  geom_point(aes(color=year), alpha=0.5) + geom_smooth(se=FALSE) +
  geom_rect(
    data=range_time,
    aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax),
    inherit.aes = FALSE, alpha=0.5) +
  geom_hline(yintercept = 3, color="gray") +
  facet_wrap(facets = vars(id), ncol=2) +
  scale_color_viridis_c(name = "Year", end = 0.8, option = "plasma") +
  labs(
    x = "Time at arrival",
    y = "Number of rainy commute per month"
  )

# plot different of number of rainy commutes between successive hours
plot_rain_model <- data_rain %>%
  filter(hour %in% 6:10) %>% 
  ggplot(aes(x=hour, y=ncm_rain_delta)) +
  geom_point(aes(color=year), alpha=0.5) + geom_smooth(se=FALSE) +
  geom_hline(yintercept = 0, color="gray") +
  facet_wrap(facets = vars(id), ncol=2) +
  scale_color_viridis_c(name = "Year", end = 0.8, option = "plasma") +
  labs(
    x = "Time at arrival",
    y = "Difference in rainy communes per month between consecutive hours"
  )

# plot change in frequency of dry commute with years
plot_rain_change <- data_rain %>% 
  filter(hour %in% 7:9) %>% 
  ggplot(aes(x=year, y=ncm_rain, color=as.factor(hour))) +
  geom_point() + geom_smooth(method = "lm") +
  geom_hline(yintercept = 3, color="grey") +
  facet_wrap(facets = vars(id), ncol=2) +
  scale_color_viridis_d(name = "Time at arrival", end = 0.8) +
  theme(legend.position = "bottom") +
  labs(
    x = NULL,
    y = "Number of rainy commute per month"
  )

# count rainy commutes
table_rain <- data_rain %>% 
  filter(hour %in% c(7:9, 18)) %>% 
  group_by(id, hour) %>% 
  summarise(
    ncm_rain = mean(ncm_rain),
    ncy_rain_strong = mean(ncm_rain_strong * 12)
    )

```

```{r figures_animation}
list_hours <- c(9, 18)

data_rain <- read_rds("data/data_frequency_rain.rds")

data_rain_subset <- data_rain %>% 
  select(id, year, hour, strong=f_rain_strong, moderate=f_rain_moderate, dry=f_dry) %>% 
  pivot_longer(cols=c(strong, moderate, dry), names_to = "rain") %>% 
  mutate(rain = factor(rain, levels = c("strong", "moderate", "dry")))

plot_frequency <- data_rain_subset %>%
  ggplot(aes(x=hour, y=value, fill=rain)) +
  geom_col(data = . %>% filter(hour %in% 9)) +
  geom_col(data = . %>% filter(hour %in% 18)) +
  geom_col(data = . %>% filter(hour %out% list_hours), alpha=0.6) +
  geom_hline(yintercept = 0.9, color="red") +
  facet_wrap(facets = vars(id), ncol=2) +
  scale_fill_viridis_d(end = 0.9) +
  labs(
    x = "Time at arrival",
    y = "Frequency over one year"
  ) + theme(legend.position = "bottom")

plot_frequency_anim <- plot_frequency + 
  transition_states(year, transition_length = 2, state_length = 1) +
  ggtitle('Hourly rain events during year {closest_state}') 
  
plot_frequency_anim %>% 
  animate(width = 600, height = 600, res = 80) %>% 
  anim_save(animation=., "rain_frequency.gif", path="R/figures")

```